=== Abbatangeli/PITre/NttDataWA/NttDataWA/Summaries/TemplateXML/XMLReport.xsd
<?xml version="1.0" ?>
<xs:schema id="report" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata"
	attributeFormDefault="qualified" elementFormDefault="qualified">
	<xs:element name="report">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="pagina">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="dta_stampa" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="align" form="unqualified" type="xs:string" />
											<xs:attribute name="target" form="unqualified" type="xs:string" />
											<xs:attribute name="font" form="unqualified" type="xs:string" />
											<xs:attribute name="size" form="unqualified" type="xs:string" />
											<xs:attribute name="style" form="unqualified" type="xs:string" />
											<xs:attribute name="color" form="unqualified" type="xs:string" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							<xs:element name="num_pagine" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="align" form="unqualified" type="xs:string" />
											<xs:attribute name="target" form="unqualified" type="xs:string" />
											<xs:attribute name="font" form="unqualified" type="xs:string" />
											<xs:attribute name="size" form="unqualified" type="xs:string" />
											<xs:attribute name="style" form="unqualified" type="xs:string" />
											<xs:attribute name="color" form="unqualified" type="xs:string" />
											<xs:attribute name="total" form="unqualified" type="xs:string" />
											<xs:attribute name="separator" form="unqualified" type="xs:string" />
											<xs:attribute name="widthTot" type="xs:string" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="formato" form="unqualified" type="xs:string" />
						<xs:attribute name="orientamento" form="unqualified" type="xs:string" />
					</xs:complexType>
				</xs:element>
				<xs:element name="header" nillable="false" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="align" form="unqualified" type="xs:string" />
								<xs:attribute name="font" form="unqualified" type="xs:string" />
								<xs:attribute name="size" form="unqualified" type="xs:string" />
								<xs:attribute name="style" form="unqualified" type="xs:string" />
								<xs:attribute name="color" form="unqualified" type="xs:string" />
								<xs:attribute name="bgcolor" form="unqualified" type="xs:string" />
								<xs:attribute name="border" form="unqualified" type="xs:string" />
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="logo" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:attribute name="align" form="unqualified" type="xs:string" />
						<xs:attribute name="file" form="unqualified" type="xs:string" />
						<xs:attribute name="bgcolor" form="unqualified" type="xs:string" />
					</xs:complexType>
				</xs:element>
				<xs:element name="dati" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:choice>
							<xs:element name="paragrafo" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="align" form="unqualified" type="xs:string" />
											<xs:attribute name="font" form="unqualified" type="xs:string" />
											<xs:attribute name="size" form="unqualified" type="xs:string" />
											<xs:attribute name="style" form="unqualified" type="xs:string" />
											<xs:attribute name="color" form="unqualified" type="xs:string" />
											<xs:attribute name="bgcolor" form="unqualified" type="xs:string" />
											<xs:attribute name="target" form="unqualified" type="xs:string" />
                                            <xs:attribute name="indentationLeft" form="unqualified" type="xs:string" />
                                            <xs:attribute name="indentationRight" form="unqualified" type="xs:string" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							<xs:element name="tabella" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="header_tabella" minOccurs="0" maxOccurs="1">
											<xs:complexType>
												<xs:attribute name="align" form="unqualified" type="xs:string" />
												<xs:attribute name="valign" form="unqualified" type="xs:string" />
												<xs:attribute name="font" form="unqualified" type="xs:string" />
												<xs:attribute name="size" form="unqualified" type="xs:string" />
												<xs:attribute name="style" form="unqualified" type="xs:string" />
												<xs:attribute name="color" form="unqualified" type="xs:string" />
												<xs:attribute name="bgcolor" form="unqualified" type="xs:string" />
											</xs:complexType>
										</xs:element>
										<xs:element name="dati_tabella" minOccurs="0" maxOccurs="1">
											<xs:complexType>
												<xs:attribute name="align" form="unqualified" type="xs:string" />
												<xs:attribute name="valign" form="unqualified" type="xs:string" />
												<xs:attribute name="font" form="unqualified" type="xs:string" />
												<xs:attribute name="size" form="unqualified" type="xs:string" />
												<xs:attribute name="style" form="unqualified" type="xs:string" />
												<xs:attribute name="color" form="unqualified" type="xs:string" />
												<xs:attribute name="bgcolor" form="unqualified" type="xs:string" />
											</xs:complexType>
										</xs:element>
										<xs:element name="colonne" minOccurs="0" maxOccurs="1">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="colonna" minOccurs="1" maxOccurs="unbounded">
														<xs:complexType>
															<xs:attribute name="name" form="unqualified" type="xs:string" />
															<xs:attribute name="alias" form="unqualified" type="xs:string" />
															<xs:attribute name="visible" form="unqualified" type="xs:string" />
															<xs:attribute name="width" form="unqualified" type="xs:string" />
															<xs:attribute name="align" form="unqualified" type="xs:string" />
															<xs:attribute name="valign" form="unqualified" type="xs:string" />
															<xs:attribute name="bgColor" type="xs:string" />                                                            
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="showBorder" form="unqualified" type="xs:string" />
									<xs:attribute name="target" form="unqualified" type="xs:string" />
									<xs:attribute name="padding" type="xs:string" />
									<xs:attribute name="spacing" type="xs:string" />
								</xs:complexType>
							</xs:element>
						</xs:choice>
					</xs:complexType>
				</xs:element>
				<xs:element name="footer" nillable="false" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="align" form="unqualified" type="xs:string" />
								<xs:attribute name="font" form="unqualified" type="xs:string" />
								<xs:attribute name="size" form="unqualified" type="xs:string" />
								<xs:attribute name="style" form="unqualified" type="xs:string" />
								<xs:attribute name="color" form="unqualified" type="xs:string" />
								<xs:attribute name="bgcolor" form="unqualified" type="xs:string" />
								<xs:attribute name="border" form="unqualified" type="xs:string" />
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Abbatangeli/PITre/BackEnd WS PIS REST/Experimental/Vt-Docs/DocsPaWS/report/templateXML/XMLRepStampaRisRicToDoList.xml
<?xml version="1.0"?>
<report xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XMLReport.xsd">
  <pagina formato="A4" orientamento="ORIZZONTALE">
    <dta_stampa align="RIGHT" target="HEADER" font="Arial" size="10" style="PLAIN" color="#000000">Stampa to do list effettuata il: </dta_stampa>
    <num_pagine align="CENTER" target="FOOTER" font="Arial" size="8" style="PLAIN" color="#000000" total="1" separator="/" widthTot="5">Pag. </num_pagine>
  </pagina>
  <header align="RIGHT" font="Arial" size="8" style="PLAIN" color="#000000" bgcolor="#FFFFFF" border="0">
  </header>
  <!--<logo align="LEFT" file="" bgcolor="#FFFFFF"/>-->
  <logo/>
  <dati>
    <paragrafo align="LEFT" font="Arial" size="14" style="BOLD" color="#000000" bgcolor="#FFFFFF" target="PAR_AMM">@amm</paragrafo>
    <paragrafo align="LEFT" font="Arial" size="14" style="BOLD" color="#000000" bgcolor="#FFFFFF" target="PAR_TITLE">@title</paragrafo>
    <paragrafo align="LEFT" font="Arial" size="10" style="NORMAL" color="#000000" bgcolor="#FFFFFF" target="PAR_TOT_RIGHE">Righe stampate: @param0</paragrafo>
  </dati>
  <dati>
    <tabella showBorder="true" target="TABLE" padding="2" spacing="0">
      <header_tabella align="CENTER" font="Arial" size="8" style="BOLD" color="#000000" bgcolor="#C0C0C0" valign="middle"/>
      <dati_tabella align="CENTER" font="Arial" size="7" style="PLAIN" color="#000000" bgcolor="#C0C0C0" valign="bottom"/>
      <colonne>
        <colonna name="DATA_INVIO" alias="Data trasm." visible="true" width="58" align="center" valign="top" bgColor="#FFFFFF" />
        <colonna name="INFO_OBJ" alias="Oggetto trasmesso" visible="true" width="400" align="left" valign="top" bgColor="#FFFFFF" />
        <colonna name="MITT" alias="Mittenti" visible="true" width="170" align="center" valign="top" bgColor="#FFFFFF" />
        <colonna name="DEST" alias="Destinatari" visible="true" width="170" align="left" valign="top" bgColor="#FFFFFF" />
      </colonne>
    </tabella>
  </dati>
  <footer align="LEFT" font="Arial" size="8" style="PLAIN" color="#000000" bgcolor="#FFFFFF" border="0">
    
  </footer>
</report>

=== Abbatangeli/PITre/BackEnd WS PIS REST/Experimental/Vt-Docs/DocsPaWA/ProspettiRiepilogativi/Frontend/TemplateXML/R_DettaglioPratica.xml
<?xml version="1.0" encoding="utf-8" ?>
<report xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XMLReport.xsd">
  <pagina formato="A4" orientamento="ORIZZONTALE">
    <dta_stampa align="RIGHT" target="footer" font="Arial" size="10" style="PLAIN" color="#000000">Stampa effettuata il: </dta_stampa>
    <num_pagine align="CENTER" target="footer" font="Arial" size="8" style="PLAIN" color="#000000" total="1" separator="/" widthTot="5">Pag. </num_pagine>
  </pagina>
  <header align="LEFT" font="Arial" size="16" style="BOLD" color="#000000" bgcolor="#FFFFFF" border="1">Stampa Dettaglio Pratica</header>
  <logo align="LEFT" file="" bgcolor="#FFFFFF"/>
  <dati>
    <paragrafo align="LEFT" font="Arial" size="10" style="BOLD" color="#000000" bgcolor="#FFFFFF" target="PAR_ANNO">Anno: @param1</paragrafo>
    <paragrafo align="LEFT" font="Arial" size="10" style="BOLD" color="#000000" bgcolor="#FFFFFF" target="PAR_CLASSIFICA">Classifica: @param2</paragrafo>
    <paragrafo align="LEFT" font="Arial" size="10" style="BOLD" color="#000000" bgcolor="#FFFFFF" target="PAR_PRATICA">Pratica: @param3</paragrafo>
    <paragrafo align="LEFT" font="Arial" size="10" style="BOLD" color="#000000" bgcolor="#FFFFFF" target="PAR_REGISTRO">Registro: @param5 - @param4</paragrafo>
  </dati>
  <dati>
    <tabella showBorder="true" target="TABLE_ANNO" padding="2" spacing="0">
      <header_tabella align="CENTER" font="Arial" size="10" style="BOLD" color="#000000" bgcolor="#C0C0C0" valign="middle"/>
      <dati_tabella align="LEFT" font="Arial" size="8" style="PLAIN" color="#000000" bgcolor="#C0C0C0" valign="bottom"/>
      <colonne>
        <colonna name="NUM_FASCICOLO" alias="Numero Atto" visible="true" width="20" align="center" valign="top"/>
        <colonna name="DESCRIZIONE" alias="Descrizione" visible="true" width="40" align="left" valign="top"/>
        <colonna name="DTA_CREAZIONE" alias="Data" visible="true" width="20" align="center" valign="top"/>        
      </colonne>
    </tabella>
  </dati>
  <footer align="LEFT" font="Arial" size="8" style="PLAIN" color="#000000" bgcolor="#FFFFFF" border="1">

  </footer>
</report>

=== Abbatangeli/PITre/NttDataWA/NttDataWA/Summaries/TemplateXML/R_DocTrasmToAOO.xml
<?xml version="1.0" encoding="utf-8"?>
<report xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XMLReport.xsd">
	<pagina formato="A4" orientamento="ORIZZONTALE">
		<dta_stampa align="RIGHT" target="footer" font="Arial" size="10" style="PLAIN" color="#000000">Stampa effettuata il: </dta_stampa>
		<num_pagine align="CENTER" target="footer" font="Arial" size="8" style="PLAIN" color="#000000" total="1" separator="/" widthTot="5">Pag. </num_pagine>
	</pagina>
	<header align="LEFT" font="Arial" size="16" style="BOLD" color="#000000" bgcolor="#FFFFFF" border="1">Rapporto annuale sui documenti spediti</header>
	<logo align="LEFT" file="" bgcolor="#FFFFFF"/>
	<dati>
		<paragrafo align="LEFT" font="Arial" size="10" style="BOLD" color="#000000" bgcolor="#FFFFFF" target="PAR_REGISTRO">@param4 - Registro: @param1 - Anno: @param2</paragrafo>
		<paragrafo align="LEFT" font="Arial" size="10" style="BOLD" color="#000000" bgcolor="#FFFFFF" target="TOT_SPED">Totale documenti spediti: @param3</paragrafo>
    <paragrafo align="LEFT" font="Arial" size="10" style="PLAIN" color="#000000" bgcolor="#FFFFFF" target="SPED_INTEROP">Documenti spediti tramite Interoperabilità: @param5</paragrafo>
    <paragrafo align="LEFT" font="Arial" size="10" style="PLAIN" color="#000000" bgcolor="#FFFFFF" target="SPED_IS">Documenti spediti tramite Interoperabilità PITRE: @param7</paragrafo>
    <paragrafo align="LEFT" font="Arial" size="10" style="PLAIN" color="#000000" bgcolor="#FFFFFF" target="SPED_MAIL">Documenti spediti tramite Mail: @param6</paragrafo>
	</dati>
  <dati>
    <paragrafo align="LEFT" font="Arial" size="10" style="BOLD" color="#000000" bgcolor="#FFFFFF" target="TOT_SPED_AMM">Documenti spediti ad altre amministrazioni: @param8</paragrafo>
  </dati>
	<dati>
		<tabella showBorder="true" target="TABLE_AMM" padding="2" spacing="0">
			<header_tabella align="CENTER" font="Arial" size="10" style="BOLD" color="#000000" bgcolor="#C0C0C0" valign="middle"/>
			<dati_tabella align="LEFT" font="Arial" size="8" style="PLAIN" color="#000000" bgcolor="#C0C0C0" valign="bottom"/>
			<colonne>
				<colonna name="VAR_COD_AMM" alias="Cod. AOO" visible="true" width="80" align="left" valign="top"/>
				<colonna name="CANALE_SPED" alias="Canale Sped." visible="true" width="70" align="left" valign="top"/>
				<colonna name="GENNAIO" alias="Gen" visible="true" width="" align="center" valign="top"/>
				<colonna name="FEBBRAIO" alias="Feb" visible="true" width="" align="center" valign="top"/>
				<colonna name="MARZO" alias="Mar" visible="true" width="" align="center" valign="top"/>
				<colonna name="APRILE" alias="Apr" visible="true" width="" align="center" valign="top"/>
				<colonna name="MAGGIO" alias="Mag" visible="true" width="" align="center" valign="top"/>
				<colonna name="GIUGNO" alias="Giu" visible="true" width="" align="center" valign="top"/>
				<colonna name="LUGLIO" alias="Lug" visible="true" width="" align="center" valign="top"/>
				<colonna name="AGOSTO" alias="Ago" visible="true" width="" align="center" valign="top"/>
				<colonna name="SETTEMBRE" alias="Set" visible="true" width="" align="center" valign="top"/>
				<colonna name="OTTOBRE" alias="Ott" visible="true" width="" align="center" valign="top"/>
				<colonna name="NOVEMBRE" alias="Nov" visible="true" width="" align="center" valign="top"/>
				<colonna name="DICEMBRE" alias="Dic" visible="true" width="" align="center" valign="top"/>
				<colonna name="TOT_M_SPED" alias="Totale" visible="true" width="" align="center" valign="top"/>
			</colonne>
		</tabella>
	</dati>
  <dati>
    <paragrafo align="LEFT" font="Arial" size="10" style="BOLD" color="#000000" bgcolor="#FFFFFF" target="TOT_SPED_PR">Documenti spediti a persone/ruoli: @param9</paragrafo>
  </dati>
  <dati>
    <tabella showBorder="true" target="TABLE_PR" padding="2" spacing="0">
      <header_tabella align="CENTER" font="Arial" size="10" style="BOLD" color="#000000" bgcolor="#C0C0C0" valign="middle"/>
      <dati_tabella align="LEFT" font="Arial" size="8" style="PLAIN" color="#000000" bgcolor="#C0C0C0" valign="bottom"/>
      <colonne>
        <colonna name="VAR_COD_AMM" alias="Cod. AOO" visible="true" width="80" align="left" valign="top"/>
        <colonna name="CANALE_SPED" alias="Canale Sped." visible="true" width="70" align="left" valign="top"/>
        <colonna name="GENNAIO" alias="Gen" visible="true" width="" align="center" valign="top"/>
        <colonna name="FEBBRAIO" alias="Feb" visible="true" width="" align="center" valign="top"/>
        <colonna name="MARZO" alias="Mar" visible="true" width="" align="center" valign="top"/>
        <colonna name="APRILE" alias="Apr" visible="true" width="" align="center" valign="top"/>
        <colonna name="MAGGIO" alias="Mag" visible="true" width="" align="center" valign="top"/>
        <colonna name="GIUGNO" alias="Giu" visible="true" width="" align="center" valign="top"/>
        <colonna name="LUGLIO" alias="Lug" visible="true" width="" align="center" valign="top"/>
        <colonna name="AGOSTO" alias="Ago" visible="true" width="" align="center" valign="top"/>
        <colonna name="SETTEMBRE" alias="Set" visible="true" width="" align="center" valign="top"/>
        <colonna name="OTTOBRE" alias="Ott" visible="true" width="" align="center" valign="top"/>
        <colonna name="NOVEMBRE" alias="Nov" visible="true" width="" align="center" valign="top"/>
        <colonna name="DICEMBRE" alias="Dic" visible="true" width="" align="center" valign="top"/>
        <colonna name="TOT_M_SPED" alias="Totale" visible="true" width="" align="center" valign="top"/>
      </colonne>
    </tabella>
  </dati>
	<footer align="LEFT" font="Arial" size="8" style="PLAIN" color="#000000" bgcolor="#FFFFFF" border="1">

	</footer>
</report>

=== Abbatangeli/PITre/Vt-Docs/DocsPaWS/report/templateXML/XMLRepStampaRegistro.xml
<?xml version="1.0"?>
<report xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XMLReport.xsd">
	<pagina formato="A4" orientamento="ORIZZONTALE">
		<dta_stampa align="RIGHT" target="footer" font="Arial" size="10" style="PLAIN" color="#000000">Stampa effettuata il: </dta_stampa>
		<num_pagine align="CENTER" target="footer" font="Arial" size="8" style="PLAIN" color="#000000" total="1" separator="/" widthTot="5">Pag. </num_pagine>
	</pagina>
	<!--<header align="RIGHT" font="Arial" size="8" style="PLAIN" color="#000000" bgcolor="#FFFFFF" border="0"></header>-->
	<!--<logo align="LEFT" file="" bgcolor="#FFFFFF"/>-->
  <header/>
  <logo/>
  <dati>
		<paragrafo align="LEFT" font="Arial" size="14" style="BOLD" color="#000000" bgcolor="#FFFFFF" target="PAR_AMMINISTRA">@paramAmm</paragrafo>
		<paragrafo align="LEFT" font="Arial" size="14" style="BOLD" color="#000000" bgcolor="#FFFFFF" target="PAR_REGISTRO">Registro: @param0</paragrafo>
		<paragrafo align="LEFT" font="Arial" size="12" style="PLAIN" color="#000000" bgcolor="#FFFFFF" target="PAR_RANGE_PROTOCOLLO">Stampa del Registro Ufficiale di Protocollo dal numero @param1 al numero @param2</paragrafo>
	</dati>
	<dati>
		<tabella showBorder="true" target="TABLE_PROTOCOLLO" padding="2" spacing="0">
			<header_tabella align="CENTER" font="Arial" size="8" style="BOLD" color="#000000" bgcolor="#C0C0C0" valign="middle"/>
			<dati_tabella align="LEFT" font="Arial" size="7" style="PLAIN" color="#000000" bgcolor="#C0C0C0" valign="bottom"/>
			<colonne>
				<colonna name="NUM_PROTO" alias="Protocollo" visible="true" width="40" align="center" valign="top" />
				<colonna name="DATA" alias="Data" visible="true" width="35" align="center" valign="top"/>
				<colonna name="DATA_ANNULLAMENTO" alias="ANNULLATO IL" visible="true" width="50" align="center" valign="top"/>
				<colonna name="CHA_TIPO_PROTO" alias="Tipo" visible="true" width="20" align="center" valign="top"/>
				<colonna name="OGGETTO" alias="Oggetto" visible="true" width="170" align="left" valign="top"/>
				<colonna name="MITT_DEST" alias="Mitt./Dest." visible="true" width="150" align="left" valign="top"/>
				<colonna name="FASCICOLI" alias="Fascicoli" visible="true" width="50" align="center" valign="top"/>
				<colonna name="IMPRONTA" alias="Impronta" visible="true" width="80" align="left" valign="top"/>
				<colonna name="N_ALLEGATI" alias="All.ti" visible="true" width="20" align="center" valign="top"/>
			</colonne>
		</tabella>
	</dati>
	<dati>
		<paragrafo align="LEFT" font="Arial" size="12" style="PLAIN" color="#000000" bgcolor="#FFFFFF" target="PAR_RANGE_VARIAZIONI">Modifiche apportate ai documenti protocollati prima del @param0</paragrafo>
	</dati>
	<dati>
		<tabella showBorder="true" target="TABLE_VARIAZIONI" padding="2" spacing="0">
			<header_tabella align="CENTER" font="Arial" size="8" style="BOLD" color="#000000" bgcolor="#C0C0C0" valign="middle"/>
			<dati_tabella align="LEFT" font="Arial" size="7" style="PLAIN" color="#000000" bgcolor="#C0C0C0" valign="bottom"/>
			<colonne>
				<colonna name="NUM_PROTO" alias="Protocollo" visible="true" width="40" align="center" valign="top"/>
				<colonna name="DATA" alias="Data" visible="true" width="35" align="center" valign="top"/>
				<colonna name="DATA_ANNULLAMENTO" alias="ANNULLATO IL" visible="true" width="50" align="center" valign="top"/>
				<colonna name="CHA_TIPO_PROTO" alias="Tipo" visible="true" width="20" align="center" valign="top"/>
				<colonna name="OGGETTO" alias="Oggetto" visible="true" width="170" align="left" valign="top"/>
				<colonna name="MITT_DEST" alias="Mitt./Dest." visible="true" width="150" align="left" valign="top"/>
				<colonna name="FASCICOLI" alias="Fascicoli" visible="true" width="50" align="center" valign="top"/>
				<colonna name="IMPRONTA" alias="Impronta" visible="true" width="80" align="left" valign="top"/>
				<colonna name="N_ALLEGATI" alias="All.ti" visible="true" width="20" align="center" valign="top"/>
			</colonne>
		</tabella>
	</dati>
  <footer align="LEFT" font="Arial" size="8" style="PLAIN" color="#000000" bgcolor="#FFFFFF" border="0">IL RESPONSABILE DEL SERVIZIO _____________________________________</footer>
</report>
